version: '2'
services:
  rumaso2-app:
    image: rumaso2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rumaso2-postgresql:5432/rumaso2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  rumaso2-postgresql:
    extends:
      file: postgresql.yml
      service: rumaso2-postgresql
